version: '3.9'

services:
  despesas-backend-api-net-core-local:
    container_name: api-in-memory-local
    image: ${DOCKER_REGISTRY-}despesasbackendapinetcore
    build:
      context: .
      dockerfile: despesas-backend-api-net-core/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - despesas-network

networks:
    despesas-network:
        driver: bridge