version: '3.4'

services:
  despesas-backend-api-net-core:
    image: alexfariakof/api-despesas-backend-netcore-img
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 42535:42535
      