version: '3.4'

services:
  despesas-backend-api-net-core-dev:
    container_name: api-in-memory-dev
    image: alexfariakof/api-despesas-backend-netcore-dev-img
    restart: always
    build:
      context: .
      dockerfile: despesas-backend-api-net-core/Dockerfile.development
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 42534:42534
    networks:
      - despesas-network

networks:
    despesas-network:
        driver: bridge