version: '3.9'
services:
  despesas-backend-local-db:
     container_name: mssql-server-in-docker
     image: mssql-server-db-img
     environment:
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Developer"
        TZ: America/Sao_Paulo
        MSSQL_DATABASE: StreamingDB
        MSSQL_USER: docker
        MSSQL_PASSWORD: docker
        SA_PASSWORD: "!aA12345"
        MSSQL_TCP_PORT: "1433"
        MSSQL_ALLOW_DUPLICATE_SQL_SERVER_NAMES: "Y"
        MSSQL_ENABLE_HADR: "N"
        MSSQL_COLLATION: "SQL_Latin1_General_CP1_CI_AS"
     ports:
        - "1433:1433"
     networks:
        - despesas-network
  
  despesas-backend-api-net-core-db-local:
    restart: always
    build:
      context: .
      dockerfile: ./Migrations.MsSqlServer/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "42534:42534"      
    depends_on:
      - despesas-backend-local-db
    networks:
      - despesas-network

networks:
    despesas-network:
        driver: bridge