version: '3.4'

services:
  despesas-backend-api-net-core:
    container_name: dev-db-in-memory
    image: alexfariakof/api-despesas-backend-netcore-dev-img
    restart: always
    build:
      context: .
      dockerfile: despesas-backend-api-net-core/Dockerfile-Development
    ports:
      - 42534:42534
    networks:
      - despesas-network
      
networks:
    despesas-network:
        driver: bridge