version: '3.4'

services:
  despesas-backend-api-net-core-local:
    container_name: api-in-memory-local
    image: alexfariakof/api-despesas-backend-netcore-img
    restart: always
    build:
      context: .
      dockerfile: despesas-backend-api-net-core/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 42535:42535
    networks:
      - despesas-network

networks:
    despesas-network:
        driver: bridge