version: '3.4'

services:
  despesas-backend-local-db:
    container_name: despesas-backend-db
    image: alexfariakof/mysql-server-db-img
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: '!12345'
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: DespesasPessoaisDB
      LANG: C.UTF-8
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_0900_ai_ci
    ports:
        - 3306:3306
    networks:
      - despesas-network
  
  despesas-backend-api-net-core-prod:
    container_name: api-net-core-prod
    image: alexfariakof/api-despesas-backend-netcore-prod-img
    restart: always
    build:
      context: .
      dockerfile: ./despesas-backend-api-net-core/Dockerfile-Production
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "42535:42535"      
    depends_on:
      - despesas-backend-local-db
    networks:
      - despesas-network

networks:
    despesas-network:
        driver: bridge