version: '3.4'

services:
  despesas-backend-api-net-core-dev:
    container_name: api-in-memory-dev
    image: alexfariakof/api-despesas-backend-netcore-dev-img
    restart: always
    build:
      context: .
      dockerfile: despesas-backend-api-net-core/Dockerfile-Development
    ports:
      - 42534:42534
    networks:
      - despesas-network
  environment:
    TZ: America/Sao_Paulo
networks:
    despesas-network:
        driver: bridge