version: '3.4'

services:
  despesas-backend-local-db:
    container_name: despesas-backend-db
    image: mysql-server-db-img
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: ./despesas-backend-api-net-core/Database-local/Dockerfile-database-local
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: '!12345'
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: DespesasPessoaisDB
      LANG: C.UTF-8
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_0900_ai_ci
    ports:
        - 3306:3306
    networks:
      - despesas-network
  
  despesas-backend-local:
    container_name: despesas-backend-api
    image: backend-api-img    
    build:
      context: .
      dockerfile: ./despesas-backend-api-net-core/Dockerfile-Database
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "42535:42535"      
    depends_on:
      - db
    networks:
      - despesas-network

networks:
    despesas-network:
        driver: bridge