name: Build and Test
on:
  workflow_call:

  push:
    branches: 
      - main 
      - dev

  pull_request:
    types: [opened]
    branches:       
      - main

permissions:
    contents: read 
jobs:
  build_and_test:
    name: Build and Test .Net
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0  

    - name: SonarCloud Scan #Reported that when working with GitHub Actions reusable workflows
      uses: SonarSource/sonarcloud-github-action@master
      env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Cache .NET packages    
      uses: actions/cache@v3
      id: dotnet-cache
      with:
        path: ~/.nuget/packages
        key: dotnet-packages-${{ github.repository }}
        restore-keys: dotnet-packages-${{ github.repository }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      if: steps.dotnet-cache.outputs.cache-hit != 'true'
      with:
        dotnet-version: 8.0.x
    
    - name: Build and Restore App 
      run: dotnet build  ./Despesas.WebApi/Despesas.WebApi.csproj --restore
      continue-on-error: false

    - name:  Test .Net App
      run: dotnet test ./XunitTests/XUnit.Tests.csproj
      continue-on-error: false  

  trigger_tests_sonarcloud:
    needs: build_and_test
    name: Test and Analysis Code In Sonar Cloud
    uses: alexfariakof/app-despesas-pessoais/.github/workflows/test_analyse_in_Sonar_Cloud.yml@main
    secrets: inherit