name: .NET Build and Test Unit
on:
  push:
    branches: 
      - main
      - dev
      - release/*
      - pre-release
      - hotfix/*
      - feature/*
      - bugfix/*

  pull_request:
    types: [opened, synchronize, reopened]

permissions:
    contents: read    
      
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache .NET packages    
      uses: actions/cache@v3
      id: dotnet-cache
      with:
        path: ~/.nuget/packages
        key: dotnet-packages-${{ github.repository }}
        restore-keys: dotnet-packages-${{ github.repository }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      if: steps.dotnet-cache.outputs.cache-hit != 'true'
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      continue-on-error: false

    - name: Build
      run: dotnet build --no-restore
      continue-on-error: false

    - name: Test
      run: dotnet test --no-build --verbosity normal
      continue-on-error: false