name: .NET Build and Test Unit
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - release/*
      - pre-release
      - hotfix/*
      - feature/*
      - FE*
      - BG-FIX*
      - bg-fix*

permissions:
    contents: read    
      
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      continue-on-error: false

    - name: Build
      run: dotnet build  --no-restore
      continue-on-error: false

    - name: Test
      run: dotnet test --no-build --verbosity normal
      continue-on-error: false