name: .NET Build and Test Unit
on:
  push:
    branches: 
      - main
      - dev
      - release/*
      - pre-release
      - hotfix/*
      - feature/*
      - bugfix/*

  pull_request:
    types: [opened, synchronize, reopened]

permissions:
    contents: read    
      
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set Cache Key
      run: echo "::set-env name=CACHE_KEY::dotnet-packages"

    - name: Cache .NET packages    
      uses: actions/cache@v2
      id: dotnet-cache
      with:
        path: ~/.nuget/packages
        key: ${{ secrets.CACHE_KEY }}
        restore-keys: dotnet-packages-

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      continue-on-error: false

    - name: Build
      run: dotnet build --no-restore
      continue-on-error: false

    - name: Test
      run: dotnet test --no-build --verbosity normal
      continue-on-error: false