name: Test and Analysis Code In Sonar Cloud
on:
  workflow_call:

  push:
    branches: 
      - hotfix/*
      - feature/*
      - bugfix/*  

  pull_request:
    types: [opened, synchronize, reopened]
    branches:       
      - dev
      - staging       
      - hotfix/*
      - feature/*
      - bugfix/*  
 
jobs:
  test_code_in_sonar:
    name: Test and Analysis Code In Sonar Cloud
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        id: cache-sonar
        uses: actions/cache@v3        
        with:        
            path: ~\sonar\cache
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
      
      - name: Create if not Exist Cache Sonar Packages
        if: steps.cache-sonar.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path ~\sonar\cache -ItemType Directory    
        
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
            path: .\.sonar\scanner
            key: ${{ runner.os }}-sonar-scanner
            restore-keys: ${{ runner.os }}-sonar-scanner                
      
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path ./.sonar/scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner

      - name: Install Angular dependencies
        run: |
          npm install npm@latest > $null 2>&1
          npm install -g @angular/core @angular/cli > $null 2>&1
          npm install > $null 2>&1
        working-directory: AngularApp

      - name: Build and analyze
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |          
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"alexfariakof_app-despesas-pessoais" /o:"alexfariakof" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"  /d:sonar.exclusions="**/XunitTests/**,  **/Migrations.MsSqlServer/**, **/Migrations.MySqlServer/**, **/HyperMedia/**, **/.documents/**, *.sql, **/Program.cs, **/Despesas.DataSeeders/**, **/Despesas.CrossCutting/**, **/*.spec.ts, **/main.ts, **/environment.*, **/app.routing.module.ts, **/__mock__/*.ts, **/*.js" /d:sonar.cs.opencover.reportsPaths="**/TestResults/coverage.opencover.xml" /d:sonar.cs.lcov.reportPaths="**/TestResults/coveragereport/lcov.info"  /d:sonar.typescript.opencover.reportsPaths="**/coverage/clover.xml" /d:sonar.typescript.lcov.reportPaths="**/coverage/lcov.info"
            dotnet tool install -g dotnet-reportgenerator-globaltool
            $projectTestPath = Get-Location
            $baseDirectory =  (Resolve-Path -Path ..).Path
            $projectAngular = (Resolve-Path -Path "$baseDirectory\AngularApp");
            $sourceDirs = "$baseDirectory\Despesas.Business;$baseDirectory\Despesas.Domain;$baseDirectory\Despesas.Repository;$baseDirectory\Despesas.WebApi;$baseDirectory\AngularApp;"
            $filefilters = "$baseDirectory\Despesas.DataSeeders\**;-$baseDirectory\Migrations.MySqlServer\**;-$baseDirectory\Migrations.MsSqlServer\**;-$baseDirectory\Despesas.CrossCutting\**;-$baseDirectory\Despesas.Business\HyperMedia\**"
            $reportPath = Join-Path -Path ($projectTestPath) -ChildPath "TestResults"
            $coveragePath = Join-Path -Path $reportPath -ChildPath "coveragereport"
            $coverageAngularPath = Join-Path -Path $projectAngular -ChildPath "coverage"

            function Wait-TestResults {
                $REPEAT_WHILE = 0
                while (-not (Test-Path $reportPath)) {
                    echo "Agaurdando TestResults..."
                    Start-Sleep -Seconds 10        
                    if ($REPEAT_WHILE -eq 6) { break }
                    $REPEAT_WHILE = $REPEAT_WHILE + 1
                }
             } 

            # Gera o Relatório de Cobertura de Código 
            dotnet test  $projectTestPath/XUnit.Tests.csproj --results-directory $reportPath /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --collect:"XPlat Code Coverage;Format=opencover"
            Wait-TestResults
            reportgenerator -reports:$projectTestPath\coverage.cobertura.xml  -targetdir:$coveragePath -reporttypes:"Html;lcov;" -sourcedirs:$sourceDirs -filefilters:-$filefilters

            # Encontra o diretório como os resultados do teste mais recente na pasta TestResults 
            $latestDir = Get-ChildItem -Directory -Path $reportPath | Where-Object { $_.Name -ne 'coveragereport' } | Sort-Object LastWriteTime -Descending | Select-Object -First 1

            # Verifica se encontrou um diretório e, em caso afirmativo, obtém o nome do diretório (GUID)
            if ($latestDir) {
                $guid = $latestDir.Name    
                $coverageXmlPath = "$projectTestPath\TestResults\$guid"
                Copy-Item -Path "$coverageXmlPath\*" -Destination $reportPath -Recurse -Force
            } else {
                Write-Output "Nenhum diretório de resultados encontrado."
            }

            # Verifica se existe a pasta node_module, e sem não existir executa npm install 
            if (-not (Test-Path $projectAngular\node_modules)) {
                $watchProcess = Start-Process npm -ArgumentList "install" -WorkingDirectory $projectAngular -NoNewWindow -PassThru
                $watchProcess.WaitForExit()	
            }

            # Executa Teste Unitários e gera o relatório de cobertura do Frontend 
            $watchProcess = Start-Process npm -ArgumentList "run", "test:coverage" -WorkingDirectory $projectAngular -NoNewWindow -PassThru
            $watchProcess.WaitForExit()
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"