name: Test and Analysis Code In Sonar Cloud
on:
  workflow_call:
  push:
    branches: 
      - hotfix/*
      - feature/*
      - bugfix/*  

  pull_request:
    types: [opened, reopened]
    branches:       
      - hotfix/*
      - feature/*
      - bugfix/*  

jobs:
  test_code_in_sonar:
    name: Test and Analysis Code In Sonar Cloud
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with:
          fetch-depth: 0  

     - name: Build and Generate Coverage Report
       run: |
            dotnet tool install -g dotnet-reportgenerator-globaltool            
            dotnet build ./XunitTests/XUnit.Tests.csproj -c Test         

     - name: SonarCloud Scan #Reported that when working with GitHub Actions reusable workflows
       uses: SonarSource/sonarcloud-github-action@master
       env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 